[package]
name = "blog_os"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "=0.9"
volatile = "=0.2.6"
spin = "0.5.2"
lazy_static = {version = "=1.5.0", features = ["spin_no_std"]}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
